name: tsvety-scrolling
version: '0.1.0'
summary: Scrolling text
description: A bunch of scrolling static strings

grade: stable
confinement: strict
base: core20
  #architectures:
  #  - build-on: arm64
  #    run-on: amd64


slots:
  dbus-tsvety-scrolling:
    interface: dbus
    bus: session
    name: org.bar.tsvety-scrolling

apps:
  tsvety-scrolling:
    command: tsvety-scrolling
    extensions: [flutter-master]
    plugs:
      - network
    slots:
      - dbus-tsvety-scrolling
parts:
  tsvety-scrolling:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart