name: tsvety-scrolling
version: '0.1.1'
summary: Scrolling text
description: A bunch of scrolling static strings

grade: stable
confinement: strict
base: core18
# architectures:
#  - build-on: arm64
#    run-on: amd64


apps:
  tsvety-scrolling:
    command: tsvety-scrolling
    extensions: [flutter-dev]

parts:
  tsvety-scrolling:
    source: https://github.com/tzvety/tsvety-scrolling.git
    plugin: flutter
    flutter-target: lib/main.dart
