name: tsvety-scrolling
version: 0.1.2
summary: Flutter scrolling
description: Static text scrolling

confinement: strict
base: core18
grade: stable

slots:
  dbus-tsvety-scrolling:
    interface: dbus
    bus: session
    name: org.bar.tsvety_scrolling

apps:
  tsvety-scrolling:
    command: tsvety-scrolling
    extensions: [flutter-beta]
    plugs:
      - network
    slots:
      - dbus-tsvety-scrolling
parts:
  tsvety-scrolling:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart